[project]
name = "scanner"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Andy Armstrong", email = "andy@hexten.net" }
]
requires-python = ">=3.14"
dependencies = [
    "imagecodecs>=2026.8.16",
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
    "pillow>=12.3.0",
    "python-sane>=2.9.2 ; sys_platform == 'linux'",
    "tifffile>=2026.9.20",
]

[project.scripts]
scanner = "scanner:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"
